# Generated by Django 5.2.7 on 2025-10-11 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('pay_period', models.CharField(max_length=100)),
                ('paid_days', models.IntegerField()),
                ('loss_of_pay_days', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_words', models.TextField()),
                ('pdf_file', models.FileField(upload_to='payslips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
